---
title: Thatvis
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@thatvis.com
owner: ThatViz
first_published: 2020
description: ''
baseurl: https://ma-jones.com.githib.io/
url: "/"
twitter_username: 
github_username: 
markdown: kramdown

theme: jekyll-theme-cayman